# Generated by Django 5.0 on 2023-12-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name_room_type',
            field=models.CharField(choices=[('standart', 'Standart Room'), ('suite', 'Suite Room'), ('lux', 'Luxury Room'), ('middle suite', 'Middle Suite Room'), ('studio', 'Studio Room')], max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.IntegerField(unique=True),
        ),
    ]
