# Generated by Django 5.0 on 2023-12-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_hotel_app', '0002_alter_room_name_room_type_alter_room_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name_room_type',
            field=models.CharField(choices=[('Standart Room', 'Standart Room'), ('Suite Room', 'Suite Room'), ('Luxury Room', 'Luxury Room'), ('Middle Suite Room', 'Middle Suite Room'), ('Studio Room', 'Studio Room')], max_length=50),
        ),
    ]
